### ISSUE TITLE
Can't access existing user

### ISSUE THREAD

**Issue by Vardiak** [nicokaiser/passport-apple#10]
Hello,
I'm trying to use this library to allow user to link an existing account to their apple ID.
But because it uses a POST request from an apple.com origin, we can't access the cookie & check if the user is already connected or not.
Is there a workaround ?

**Comment by nicokaiser** [comment]
Why can't you access the cookie? Cookies are submitted when using POST (however, there may be issues when using `SameSite=strict`)...

**Comment by Vardiak** [comment]
I can confirm the issue comes from SameSite=strict (which is enforced on Chrome if not specified). Is there any other way to access the user ? Do we have to use a POST request and not a GET callback (like other oauth libraries).
