### ISSUE TITLE
Support custom strategy name

### ISSUE THREAD

**Issue by feimosi** [nicokaiser/passport-apple#12]
I think it's worth it to allow passing custom strategy name to the constructor.
Here:
https://github.com/nicokaiser/passport-apple/blob/91fc9dcb86c9c283d00866a11b3c5a5d6017e6af/lib/strategy.js#L38

**Rationale:**
Apple sign-in requires separate client IDs for iOS and web authentication therefore it's not possible to reuse a single setup for both. I had to create two AppleStrategy instances and override `appleStrategy.name` to support both sign-ins with passport.

It's all working flawlessly now but it would be great to support it officially (e.g. to avoid breaking changes in the future).

**Comment by nicokaiser** [comment]
Did you try specifying the name in your `passport.use()` call? You can override the default name ("apple") there:

```js
passport.use('apple-client1', new AppleStrategy({ clientID: 'client1', …));
passport.use('apple-client1', new AppleStrategy({ clientID: 'client2', …));

app.get('/auth/apple1', passport.authenticate('apple-client1'));
app.get('/auth/apple2', passport.authenticate('apple-client2'));
```

**Comment by feimosi** [comment]
Oh, I didn't realize that, works perfectly now, thanks!
