### ISSUE TITLE
User data?

### ISSUE THREAD

**Issue by geekpulp** [nicokaiser/passport-apple#13]
Hey thanks for your work on this. I’m very new to development so it’s super helpful.

I’m working on implementing it but have an issue trying to get user data to save. My current code is below, but I’m unsure where to draw the user info from. I though it might work like other strategies where you profile.id, profile.displayName stuff would have the values in them. The id seems to work but so far no user data seems to be making it? Any tips?

```
// Apple passport strategy
passport.use( new AppleStrategy( {
		clientID: “xxx.xxxxx.xxx”,
		teamID: “xxxxxxxxxxx”,
		keyID: “Xxxxxxxxx”,
		key: fs.readFileSync( path.resolve( “config/Xxxxx.xxx” ) ),
		scope: [ “name”, “email” ],
		callbackURL: process.env.OOOSHINY_DOMAIN + “/users/login/apple/callback”
	},
	function ( accessToken, refreshToken, profile, done ) {
		User.findOne( {
			idToken: profile.id
		}, function ( err, user ) {
			if ( err ) {
				console.log( err );
			}
			//No user was found... so create a new user with values from Apple
			if ( user && user !== null ) {
				console.log( “Login user” );
				return done( null, user );
			} else {
				console.log( “Create user” );
				user = new User( {
                                         username: profile.displayName,
					email: profile.email

					//now in the future searching on User.findOne will match because of this next line
					idToken: profile.id,
				} );
				user.save( function ( err ) {
					if ( err ) {
						console.log( err );
					} else {
						console.log( “saving user ...” );
						return done( err, user );
					}
				} );
			}
		} );
	} ) );
```

**Comment by nicokaiser** [comment]
This is exactly how it works. The `profile.id` property should be working every time, is it?

The other properties however (`profile.name` and `property.email`) are only returned the first time a user logs into your site with Sign in With Apple (and, only if the user decides to share these properties with your site).

A returning user record never has the `name` and `email` properties. You can test this by removing the permission for your site in your own Apple ID "Sign in with Apple" settings: once you use SIWA for your site again, you are asked (once) which data you want to share, and then the site gets these data (once).

**Comment by ad-on-is** [comment]
When I authenticate via authorizationCode I get the id, email and emailVerified every time, but no name is returned.

**Comment by nicokaiser** [comment]
How do you receive the email/emailVerified? Can you check if the name is being returned (via HTTP POST) the first time a new user logs in?

**Comment by ad-on-is** [comment]
```
...
{
      clientID: "xxx",
      teamID: "xxx",
      callbackURL: null,
      keyID: "xxx",
      key: fs.readFileSync(path.join(__dirname, "AuthKey_xxx.p8")),
      scope: ["name", "email"],
   },
    async function (accessToken, refreshToken, profile, done) {
      console.log(profile);
...
```

the console.log outputs an object with id, email and emailVerified

Is there a way how I can log the user out somehow? Right now, I'm just sending login-request to the server to debug the data returned by apple for further use.

**Comment by nicokaiser** [comment]
You need to log into https://appleid.apple.com and look for something like "Apps and sites that use your Apple ID". There you can deauthorize your app. The next time you log into your app via Apple, you should receive the `name` property (but only once).

**Comment by ad-on-is** [comment]
Yes... I just found the same settings on my iPhone.. (btw, sorry, no apple/iphone user) and deleted the identifier from within there. 

Now, when the sign-in overlay pops up, I see Name (which I can edit), E-Mail (share my email) and Hide my email. So, I'm assuming these are the scopes granted for the token to be used serverside.

After clicking on continue and watching my nodejs-logs, I still don't see the name.

**Comment by ad-on-is** [comment]
I just debugged your strategy.js and `req.body` only contains the `code` which I send via the app and `jwtClaims` contains the email and the email_verified parameters. So, I assume Apple's sign-in method with a token does not return the user`s name.

**Comment by autopulated** [comment]
@ad-on-is on device you'll get the name in the app from `authorizationController(controller:didCompleteWithAuthorization:)` (see here: https://developer.apple.com/documentation/authenticationservices/implementing_user_authentication_with_sign_in_with_apple) before you submit your token to the web service for verification.

You could post the name as `body.user:{name:"...."}` in the same request you use to post the token if you need it server-side.

**Comment by ad-on-is** [comment]
@autopulated yes, that's eventually how I ended up doing it. But I thought I could get the name on the server-side, by just providing the token, as it is the case with facebook and google.
