### ISSUE TITLE
Using as a server-side login for an app

### ISSUE THREAD

**Issue by ad-on-is** [nicokaiser/passport-apple#15]
Right now I'm working on a Flutter app which provides google, facebook and apple sign-in methods.

In the app I only retreive the `access_token` from google and facebook, which I then send to my server. The server uses this access token and retreives the user-info (name, email) based on that access token. Serverside everything is done with passport, passport-google-token and passport-apple-token strategies.

Is there a similar way to do the auth with your library? It requires a callback-URL which my app simply does not have.

**Comment by ad-on-is** [comment]
I didn't see that I can provide the authorizationCode as `code` via post... so great that this functionality is included.

**Comment by nealoke** [comment]
@ad-on-is Could you share how you implemented this as I am struggling to understand how to correctly pass the code and if there are other parameters required as well. Thanks!

**Comment by ad-on-is** [comment]
> @ad-on-is Could you share how you implemented this as I am struggling to understand how to correctly pass the code and if there are other parameters required as well. Thanks!

Sure.
The POST data really has just to be like this

```
{'code': 'appleauthcode', 'user': {'name': 'first and last', 'email': 'user@example.com'}}
```

Since this library cannot obtain user data, you have to pass it from within your app, where you will get the info only for the first time when you sign into your app.

No matter what apple-signin-method you use in your app, make sure the `appleauthcode` is a String. In my case (Flutter) I had to do something like `String.fromCharCodes(result.credential.authorizationCode)`

I hope that helps.

**Comment by nealoke** [comment]
Thanks for the fast reply 👍 

So if I understand correctly you use only the "callback" part of this library and pass the `code` and `user` data to it? And this library will basically use that code to fetch other things?

So this is will be working?

```js
export default new AppleTokenStrategy(
	{
		clientID: process.env.APPLE_CLIENT_ID,
                teamID: "team",
		keyID: "key",
		key: process.env.APPLE_CLIENT_KEY,
		scope: ["name", "email"],
		callbackURL: `${urls.api}/auth/apple/token`
	},
	async (accessToken, refreshToken, { id, name: { firstName, lastName }, email }, done) => {
		let user = await User.get({ email: email.toLowerCase() });

		// Update user
		if (user) {
			user = await User.update(user.id, {
				appleId: id,
				firstName: !user.firstName ? firstName : undefined,
				lastName: !user.lastName ? lastName : undefined
			});
		}

		// Create new user
		if (!user) {
			user = await User.create({
				email,
				appleId: id,
				firstName,
				lastName
			});
		}

		return done(null, user);
	}
);
```

**Comment by ad-on-is** [comment]
No, I don't use the callback at all

```
module.exports = {

  apple: function (db) {
    return new AppleStrategy({
        clientID: "com.example.app",
        teamID: "TEAMID",
        callbackURL: null,
        keyID: "KEYID",
        key: fs.readFileSync(path.join(__dirname, "KEYFILE.p8")),
        scope: ["name", "email"],
      },
      async function (accessToken, refreshToken, profile, done) {

        let userData = {
          provider: "apple",
          id: profile.id,
          fullName: profile.name,
          name: profile.name.split(" ")[0],
          email: profile.email,
        };

      }
    );
  },

}

```

and the corresponding route is as follows, which may very depending on your implementations

```
router.post(
    "/login/apple",
    passport.authenticate("apple", {
      failWithError: true
    }),
    asyncHandler(async function (req, res) {
      if (req.user == null) {
        throw createError();
      }
      createResponse(200, null, req, res);
    })
  );

```

**Comment by nealoke** [comment]
I still can't get this to work for some reason. I'm sorry to ask but could you maybe also show all the pieces together because I really don't know what else to do 😢 .

**Comment by ad-on-is** [comment]
What exactly is not working? What errors do you get?

**Comment by LohithaYalavarthi** [comment]
@ad-on-is @nealoke 
I have been using the For eg: "https://example.com/auth/apple/callback"(This is not the actual URL I am using- but looks similar to this, instead of example.com I am using some other domain )-> this is configured as a return URL in the apple developer account

I am using the return URL as callback URL for apple config

But on the success authenticates it does navigates to this callback url-> but throws an internal server error why??

Please let me know if I am missing something

<img width="626" alt="Screenshot 2020-09-22 at 5 09 44 PM" src="https://user-images.githubusercontent.com/42953972/93877729-86168a80-fcf6-11ea-9e9f-9e6d553049e9.png">
