### ISSUE TITLE
Strategy middleware paramenters

### ISSUE THREAD

**Issue by hatemalimam** [nicokaiser/passport-apple#19]
In my case the right parameters to the strategy middleware are as follows:

```
{
      clientID: ...,
      teamID: ...,
      callbackURL: ...,
      keyID: ...,
      scope: ...,
      key: ...
      passReqToCallback: true
    },
    async (request, accessToken, refreshToken, profile, cb) => {
      const { id, name, email, emailVerified } = profile;

```

whereas in the documentation it's as follows:

```
passport.use(new AppleStrategy({
    clientID: ...
    teamID: ....
    keyID: ...
    key: ....
  },
  (accessToken, refreshToken, profile, cb) => {
```

I suspect that's due to the `passReqToCallback` set to true, if that's so it would be nice to be mentioned in the documentation.

Thanks.

**Comment by nicokaiser** [comment]
Thanks for this suggestion. This works for many Passport strategies, so I thought it might be known. However I added a paragraph in README about this.
