### ISSUE TITLE
Throws status 500 -internal server error for apple callback url 

### ISSUE THREAD

**Issue by LohithaYalavarthi** [nicokaiser/passport-apple#22]
Hi, 
@nicokaiser 
I have been using the 
For eg: "https://example.com/auth/apple/callback"(This is not the actual URL I am using- but looks similar to this, instead of example.com I am using some other domain )-> this is configured as a return URL in the apple developer account

I am using the return URL as callback URL  for apple config

In the Apple developer document -> they mentioned that we don't have to upload a file server to register the domain-> so I skipped only that specific step, which is written in your documentation which says the verify the domain

But on the success authenticates it does navigates to this callback -> but throws an internal server error why??

Please let me know if I am missing something

**Comment by nicokaiser** [comment]
Did you find anything on the server side? If the server on the callback URL, your server should display some kind of error information and what happened...

**Comment by LohithaYalavarthi** [comment]
<img width="1091" alt="Screenshot 2020-09-22 at 5 19 46 PM" src="https://user-images.githubusercontent.com/42953972/93878518-d6dab300-fcf7-11ea-84ef-53593df1eb47.png">
It only throws this error nothing else..

**Comment by LohithaYalavarthi** [comment]
@nicokaiser It throws only this in console 

<img width="1045" alt="Screenshot 2020-09-22 at 5 23 24 PM" src="https://user-images.githubusercontent.com/42953972/93878914-76984100-fcf8-11ea-9339-0f0aaa228553.png">

**Comment by nicokaiser** [comment]
The interesting bit would be the output of the server.
If you cannot access the server output, it might get a bit complicated. You can, for development(!), use the `errorhandler` module to expose all server errors to the client to be able to see the message:

```
app.use(errorHandler());
`
``

**Comment by LohithaYalavarthi** [comment]
after I inserted the code of the above one you mentioned recieved this error
<img width="1431" alt="Screenshot 2020-09-23 at 10 23 40 AM" src="https://user-images.githubusercontent.com/42953972/93968304-ece38480-fd86-11ea-9ebd-b7bb6992b115.png">

**Comment by LohithaYalavarthi** [comment]
After googling I found the error could be in the private key- I resolved that issue of the previous error and facing some other issue -It redirects to some /undefined for some reason 
<img width="1388" alt="Screenshot 2020-09-23 at 11 57 36 AM" src="https://user-images.githubusercontent.com/42953972/93974800-ffb08600-fd93-11ea-8705-347ddc4f0ec1.png">

**Comment by LohithaYalavarthi** [comment]
Everything seems to works fine @nicokaiser  thank you so much for sparing time..

**Comment by nicokaiser** [comment]
Great to hear! I can imagine that handling the private key on Windows is a bit more complicated, but glad to hear that you figured it out!
