### ISSUE TITLE
'profile' empty (only id)

### ISSUE THREAD

**Issue by marcorm** [nicokaiser/passport-apple#3]
Hi @nicokaiser . Thx for your fork, that tries to solve the orginal repo issues...

Do you know why i only get:
profile { id: '000789.XXXXXXXXXXXX.1446' }
in my profile callback?

In the docs you mention this:
`Note that the name and email properties are only returned on the first login the user.`

Does it mean that if i missed it the first time, now i can't get them anymore?

Thx a lot

**Comment by nicokaiser** [comment]
Exactly this. Apple only returns the `name` and `email` information on the first login. if you miss it, you cannot get them anymore, unless the user deletes your site in their "Sign in with Apple" settings in the Apple ID.
