### ISSUE TITLE
Cannot get user`s email and name

### ISSUE THREAD

**Issue by RomanSolianik** [nicokaiser/passport-apple#4]
Hello, Apple is not returning user`s email and name (or it is a bug in our site).
scope is configured like this:

` scope: ['name', 'email']`

And I also can see that scope in the requests to Apple.

This feature is still not implemented by Apple or it is a issue on our side?

**Comment by nicokaiser** [comment]
Apple only returns `name` and `email` for each customer the *very first time* they log in to your site.
Can you try to remove the site you are implementing, in the "Sign in with Apple" settings on your Apple ID settings? Then you will asked again if you want to submit name and email, when you use Sign in with Apple again, and then this data should be submitted (once!).

**Comment by RomanSolianik** [comment]
Thanks, I will try. I see something like that in the readme, but I remember I saw somewhere that this is not implemented by apple yet

**Comment by RomanSolianik** [comment]
It work as you said, but only name is sent once on first login, email is sent every time. Thanks
