### ISSUE TITLE
Authentication failed only apple reviewer's device

### ISSUE THREAD

**Issue by nameEO** [nicokaiser/passport-apple#57]
Hello!
I encountered weird problem that it is SIWA not working only apple reviewer's device...
Maybe **'nonce'** is a key of problem. It may not optional when using apple reviewer's account.
I notice that this package's recent codebase will take care of the problem, So I applied it and **it works**.

Do you have any **plan for release new version of this package** to npm?

**Comment by nicokaiser** [comment]
Please try version 1.0.0, I just published a new version.
