### ISSUE TITLE
Cannot find module './state/null'

### ISSUE THREAD

**Issue by noo-zh** [nicokaiser/passport-apple#82]
I am getting following error when trying to use this library:

```
Error: Cannot find module './state/null'
Require stack:
- /node_modules/@nicokaiser/passport-apple/lib/strategy.js
- /node_modules/@nicokaiser/passport-apple/lib/index.js
```

Looking at the built NPM package https://www.npmjs.com/package/@nicokaiser/passport-apple?activeTab=code, I can see there are only index and strategy js files in the lib/ folder, both state/ and errors/ folders are missing there.

Can you please fix it? :-)

**Comment by nicokaiser** [comment]
Thanks, nice catch! My optimization was probably a bit too much.
